pipeline:
  name: demo-app
  identifier: demoapp
  projectIdentifier: mymodernapp
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitrepoconnector
        repoName: vks-gitops-demo
        build: <+input>
  stages:
    - stage:
        name: Build and Push
        identifier: Build_and_Push
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerregistryconnector
                    repo: mylesg655/design-libraries
                    tags:
                      - adservice-<+pipeline.executionId>
                    dockerfile: ./microservices-demo/src/adservice/Dockerfile
                    context: ./microservices-demo/src/adservice/
